set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins'
set-option -sa terminal-overrides ",xterm*:Tc"
set -g base-index 1
set -g default-command "${SHELL}"
set -g mouse off


# Plugins

# manager
set -g @plugin 'tmux-plugins/tpm'

# these 2 just resurrect it
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# status bar
set -g status-position bottom
set -g status-justify centre
set -g status-style 'bg=default fg=default'
set -g status-left ' #S  '
set -g status-right ''
set -g status-left-length 40
set -g status-right-length 0
set -g window-status-format '#[fg=brightblack] #W '
set -g window-status-current-format '#[fg=white,bold] *#W '
set -g window-status-separator '    '
set -g window-status-style 'bg=default'
set -g window-status-current-style 'bg=default'

# Continuum
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'
set -g @resurrect-capture-pane-contents 'on'

# Keybinds
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key a display-popup -E -w 40% -h 40% -b rounded "~/.config/scripts/tmux-windowizer.sh"
bind-key f display-popup -E -w 40% -h 40% -b rounded "~/.config/scripts/tmux-sessionizer.sh"


bind-key g display-popup -E -w 90% -h 90% "lazygit"

# init tpm
run '~/.tmux/plugins/tpm/tpm'



